/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v4.22.2
// source: contacts.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./contacts_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ContactServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ContactServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.ContactList>}
 */
const methodDescriptor_ContactService_getAll = new grpc.web.MethodDescriptor(
  '/ContactService/getAll',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.ContactList,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ContactList.deserializeBinary
);


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ContactList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ContactList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.getAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/getAll',
      request,
      metadata || {},
      methodDescriptor_ContactService_getAll,
      callback);
};


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ContactList>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.getAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/getAll',
      request,
      metadata || {},
      methodDescriptor_ContactService_getAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Contacts,
 *   !proto.Contacts>}
 */
const methodDescriptor_ContactService_AddContact = new grpc.web.MethodDescriptor(
  '/ContactService/AddContact',
  grpc.web.MethodType.UNARY,
  proto.Contacts,
  proto.Contacts,
  /**
   * @param {!proto.Contacts} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Contacts.deserializeBinary
);


/**
 * @param {!proto.Contacts} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Contacts)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Contacts>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.addContact =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/AddContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_AddContact,
      callback);
};


/**
 * @param {!proto.Contacts} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Contacts>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.addContact =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/AddContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_AddContact);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Contact_id,
 *   !proto.Empty>}
 */
const methodDescriptor_ContactService_deleteContact = new grpc.web.MethodDescriptor(
  '/ContactService/deleteContact',
  grpc.web.MethodType.UNARY,
  proto.Contact_id,
  proto.Empty,
  /**
   * @param {!proto.Contact_id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.deleteContact =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/deleteContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_deleteContact,
      callback);
};


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.deleteContact =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/deleteContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_deleteContact);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Contact_id,
 *   !proto.Contacts>}
 */
const methodDescriptor_ContactService_updateContact = new grpc.web.MethodDescriptor(
  '/ContactService/updateContact',
  grpc.web.MethodType.UNARY,
  proto.Contact_id,
  proto.Contacts,
  /**
   * @param {!proto.Contact_id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Contacts.deserializeBinary
);


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Contacts)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Contacts>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.updateContact =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/updateContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_updateContact,
      callback);
};


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Contacts>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.updateContact =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/updateContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_updateContact);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Contact_id,
 *   !proto.Contacts>}
 */
const methodDescriptor_ContactService_getContact = new grpc.web.MethodDescriptor(
  '/ContactService/getContact',
  grpc.web.MethodType.UNARY,
  proto.Contact_id,
  proto.Contacts,
  /**
   * @param {!proto.Contact_id} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Contacts.deserializeBinary
);


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Contacts)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Contacts>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.getContact =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/getContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_getContact,
      callback);
};


/**
 * @param {!proto.Contact_id} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Contacts>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.getContact =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/getContact',
      request,
      metadata || {},
      methodDescriptor_ContactService_getContact);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.Empty>}
 */
const methodDescriptor_ContactService_createDatabase = new grpc.web.MethodDescriptor(
  '/ContactService/createDatabase',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.Empty,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.createDatabase =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/createDatabase',
      request,
      metadata || {},
      methodDescriptor_ContactService_createDatabase,
      callback);
};


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.createDatabase =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/createDatabase',
      request,
      metadata || {},
      methodDescriptor_ContactService_createDatabase);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.Empty>}
 */
const methodDescriptor_ContactService_deleteDatabase = new grpc.web.MethodDescriptor(
  '/ContactService/deleteDatabase',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.Empty,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ContactServiceClient.prototype.deleteDatabase =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ContactService/deleteDatabase',
      request,
      metadata || {},
      methodDescriptor_ContactService_deleteDatabase,
      callback);
};


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ContactServicePromiseClient.prototype.deleteDatabase =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ContactService/deleteDatabase',
      request,
      metadata || {},
      methodDescriptor_ContactService_deleteDatabase);
};


module.exports = proto;

